# Generated by Django 4.0.2 on 2022-02-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=20)),
                ('phno', models.IntegerField()),
                ('adhar', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('pan', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
